### PR TITLE
Allow listening port to be changed

### PR DESCRIPTION
**Pull request by chuckha**
This will default the port to 8000 but give users the opportunity to change the port this application listens on should they need it.

### CODE REVIEW

**Comment by andmarios** [comment]
Hey @chuckha , thanks for the PR. Can I ask what your use case is for this?

I am a bit skeptical because the docker way is to document your exposed ports via the EXPOSE command ( https://github.com/Landoop/schema-registry-ui/blob/master/docker/Dockerfile#L28 ) and in most scenarios you can translate the port to another one, like `docker run -p 80:8000`.

There is one scenario though where you can't translate the port, namely when you use `net=host`. Is this your issue?

**Comment by chuckha** [comment]
Yeah, that would be the one case where this is useful!

No worries if you don't think this makes sense in this project though! Feel free to close :)

Mobile.

**Comment by chuckha** [comment]
As a followup, I see other Dockerfiles `EXPOSE`ing a default port and that's how I was approaching this change. I don't know if that is best practice or not. It does seem a bit funky to expose an unused port.

**Comment by chuckha** [comment]
as it turns out, i was being dumb and don't need this. I'm closing. Thanks for the fast and thoughtful response :)

**Comment by andmarios** [comment]
Hey, sorry for the very late response. Your PR was legit, we just try to keep things as simple as possible for these images, this is why I asked about your use case before merging.

Thanks for using our images and taking time to report things!

**Pull request closed without merging**
